---
  - name: Check if DraERP App exists
    stat: path="{{ bench_path }}/apps/draerp"
    register: app

  - name: Get the DraERP app
    command: bench get-app draerp {{ draerp_repo_url }} --branch {{ draerp_branch }}
    args:
      creates: "{{ bench_path }}/apps/draerp"
      chdir: "{{ bench_path }}"
    when: not app.stat.exists and not without_draerp

  - name: Check whether the site already exists
    stat: path="{{ bench_path }}/sites/{{ site }}"
    register: site_folder
    when: not without_site

  - name: Create a new site
    command: "bench new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not site_folder.stat.exists

  - name: Install DraERP to default site
    command: "bench --site {{ site }} install-app draerp"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not without_draerp
...